language: java
install: skip
os: linux
dist: trusty
jdk: oraclejdk11 #openjdk8

addons:
  sonarcloud:
    organization: "devapps-grupo"

script:
  - ./gradlew clean build
  - ./gradlew test
  - sonar-scanner
