language: java
install: skip
os: linux
dist: trusty
jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "devapps-grupo" # the key of the org you chose at step #3
    token:
      secure: "RgBPDW5QgCsb48tAbMVjVj1RU3kjxuEoEvnmGKh6Nv2tw0T55rp32TGEPQcmYkb2wul171pez2a78YaMm0chRM6E0frSQzXP232ffPAUJKCtU25T+UqRt6ROsP6pbS+l1fzFnVrk+V5vBnbah5+cXfp4qUVlsQSBWJJa7sDN4myjgvFzqF8Ix6zrtsvpu6DKuD2EzZMszQs6cO2eohv2aKp+0p03PiJbSmdU9vhRVFrPuL3puzIxggZ979eiuPqelqjb8ss97CbwAEmTwXs0iZRI1tmqQcJeKrPXSC2Yd4djO5SREREl+xt6O4S0yEuS/2wkhlSIlmeB50Umeme/g4PGYvb+/8AH5cGTYpCbSR3oAiRSc59vF89PE+tjUevKbFv7mO9dJakeNHnwCYJ/G/yvTlJ+ES+qprnL3Zhvf4tNzll3zED8tMf7MdHRUlTIojqA1kFMKNKW8Pj1G6btFZ8U8+l5/Lu07TT7sTQCV7Pgj6+PnTJUsrUrd3JVPneP6Husq9Q5Mcj70dJG5ivb9S+vk2Mnpgysb+a21Kaht0EnVECMKyN9PoTZIIkuKz2Rt4iCLYdrwKEH9BVyMsO/5f33hGUo6eXePj5H2D0UhS/SV5Ww0It5wl30ghCHOAYHZyIiK8ep84gkpySy7h19Fylf+sOpnHZM6WO4RY579Uc=" # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  - "./gradlew build"

#env:
#  global:
#    secure: RgBPDW5QgCsb48tAbMVjVj1RU3kjxuEoEvnmGKh6Nv2tw0T55rp32TGEPQcmYkb2wul171pez2a78YaMm0chRM6E0frSQzXP232ffPAUJKCtU25T+UqRt6ROsP6pbS+l1fzFnVrk+V5vBnbah5+cXfp4qUVlsQSBWJJa7sDN4myjgvFzqF8Ix6zrtsvpu6DKuD2EzZMszQs6cO2eohv2aKp+0p03PiJbSmdU9vhRVFrPuL3puzIxggZ979eiuPqelqjb8ss97CbwAEmTwXs0iZRI1tmqQcJeKrPXSC2Yd4djO5SREREl+xt6O4S0yEuS/2wkhlSIlmeB50Umeme/g4PGYvb+/8AH5cGTYpCbSR3oAiRSc59vF89PE+tjUevKbFv7mO9dJakeNHnwCYJ/G/yvTlJ+ES+qprnL3Zhvf4tNzll3zED8tMf7MdHRUlTIojqA1kFMKNKW8Pj1G6btFZ8U8+l5/Lu07TT7sTQCV7Pgj6+PnTJUsrUrd3JVPneP6Husq9Q5Mcj70dJG5ivb9S+vk2Mnpgysb+a21Kaht0EnVECMKyN9PoTZIIkuKz2Rt4iCLYdrwKEH9BVyMsO/5f33hGUo6eXePj5H2D0UhS/SV5Ww0It5wl30ghCHOAYHZyIiK8ep84gkpySy7h19Fylf+sOpnHZM6WO4RY579Uc=
