language: java
install: skip
os: linux
dist: trusty
jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "devapps-grupo"

script:
  - sonar-scanner -Dproject.settings=sonar-project.properties
  - ./gradlew build