language: java
install: skip
os: linux
dist: xenial
jdk: openjdk11
node_js:
  - lts/*

addons:
  sonarcloud:
    organization: "devapps-grupo"

script:
  - sonar-scanner -Dproject.settings=sonar-project.properties
  - ./gradlew build

