language: java
install: skip
os: linux
dist: trusty
jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "devapps-grupo"

script:
  - ./gradlew clean build
  - ./gradlew test

after_success:
  - sonar-scanner
  #- ./gradlew build jacocoTestReport sonarqube
  
