language: java
install: skip
os: linux
dist: trusty
jdk: oraclejdk11
sudo: required
env:
  global:
  - secure: RgBPDW5QgCsb48tAbMVjVj1RU3kjxuEoEvnmGKh6Nv2tw0T55rp32TGEPQcmYkb2wul171pez2a78YaMm0chRM6E0frSQzXP232ffPAUJKCtU25T+UqRt6ROsP6pbS+l1fzFnVrk+V5vBnbah5+cXfp4qUVlsQSBWJJa7sDN4myjgvFzqF8Ix6zrtsvpu6DKuD2EzZMszQs6cO2eohv2aKp+0p03PiJbSmdU9vhRVFrPuL3puzIxggZ979eiuPqelqjb8ss97CbwAEmTwXs0iZRI1tmqQcJeKrPXSC2Yd4djO5SREREl+xt6O4S0yEuS/2wkhlSIlmeB50Umeme/g4PGYvb+/8AH5cGTYpCbSR3oAiRSc59vF89PE+tjUevKbFv7mO9dJakeNHnwCYJ/G/yvTlJ+ES+qprnL3Zhvf4tNzll3zED8tMf7MdHRUlTIojqA1kFMKNKW8Pj1G6btFZ8U8+l5/Lu07TT7sTQCV7Pgj6+PnTJUsrUrd3JVPneP6Husq9Q5Mcj70dJG5ivb9S+vk2Mnpgysb+a21Kaht0EnVECMKyN9PoTZIIkuKz2Rt4iCLYdrwKEH9BVyMsO/5f33hGUo6eXePj5H2D0UhS/SV5Ww0It5wl30ghCHOAYHZyIiK8ep84gkpySy7h19Fylf+sOpnHZM6WO4RY579Uc=
  - secure: pfaYIZD2yxK2nDAJPhDaSOQkDuNlipAhU6MOdPp9/kLJ0jqyJhByoqxMSWkdwAQI9DvnfEuhU451AOuJAWFslEAAjh7Nsveh6+NH7pHu2SRMyBz0tWw52jXHMQiEbxJd/KLRxlnRmnMEQ+mFmrZKgaNcZoyU4XxCUr+1bAOKmOlvFS1SmfI381eiHEAVUqsKCfqYM6DHm6RXTfHt+wTjTz0+Qw1vvX5zp9Wbva74Uj5eJFu0bX3G2O3uBVVnOiDZn3ae6weKu9MHTcw6LOoqu4USATLAsKqvyffo2ZXVQEHENUceaOn/QvqlxgizqfbeaOePCHMxnLLFPT2Ym8G/JNdTvvEhjxrnvuB9C4bzENLtoO6VAC0tSXHsQU4UfCxgdQDFH+rySlV82iwpAW5jfo0/mtuuHy3bwSe1GFKCMIjssjUiNShbojZDlVI+i+vzmGDJKNKvdCQUG8TV+Wcvb5SsEKplHIElFKJmsTBqLl3m0QdqN53Hd8WEQOsXYA5GdsTzbTBhadRYHYc67JmZZvUYYHnBKOEuQj/5aGo7F1fb8vAPnD6Leq0IWdTmN3PyMrF6Ng/b8q6m3jBIF4RvMY8oL8zd7gSlogM8eaooZlE28SakJDCnrz4f0g2y5fzO1FydxW9VE1c+VmaJ4cYXREidOp6D7dhttUcjZiAjIe4=
addons:
  sonarcloud:
    organization: devapps-grupo
    token:
      secure: "$SONAR_TOKEN"
script:
- sonar-scanner
- "./gradlew build"
