language: java
install: skip
os: linux
dist: trusty
jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "devapps-grupo"

script:
  - ./gradlew build
  - ./gradlew test
  - ./gradlew sonarqube
  #- sonar-scanner -Dproject.settings=sonar-project.properties
  
